// src/components/atoms/v-avatar.vue
<script setup lang="ts">
import { computed } from 'vue';
import type { AvatarSize, VAvatarProps } from '@/types/v-avatar';

const props = withDefaults(defineProps<VAvatarProps>(), {
  alt: 'avatar',
  size: 'md',
  shape: 'rounded',
  mask: '',
  online: false,
  offline: false,
  placeholder: false,
  text: '',
  ring: false,
  priority: false,
});

const sizeClasses: Record<AvatarSize, string> = {
  xs: 'w-8',
  sm: 'w-12',
  md: 'w-16',
  lg: 'w-24',
  xl: 'w-64',
};

const avatarClass = computed(() => [
  'avatar',
  {
    'avatar-online': props.online,
    'avatar-offline': props.offline,
    'avatar-placeholder': props.placeholder || !props.src,
  },
]);

const innerClass = computed(() => [
  sizeClasses[props.size],
  props.shape,
  props.mask,
  {
    'ring-2 ring-primary ring-offset-base-100 ring-offset-2': props.ring,
    'bg-neutral text-neutral-content': props.placeholder || !props.src,
  },
]);

const textClass = computed(() => {
  if (props.text.length > 2) {
    return {
      xs: 'text-xs',
      sm: 'text-sm',
      md: 'text-base',
      lg: 'text-lg',
      xl: 'text-2xl',
    }[props.size];
  }
  return {
    xs: 'text-xs',
    sm: 'text-base',
    md: 'text-xl',
    lg: 'text-3xl',
    xl: 'text-5xl',
  }[props.size];
});

const imgLoading = computed(() => (props.priority ? 'eager' : 'lazy'));
const imgFetchPriority = computed(() => (props.priority ? 'high' : 'auto'));
</script>

<template>
  <div :class="avatarClass">
    <div :class="innerClass">
      <img
        v-if="src"
        :src="src"
        :alt="alt"
        :loading="imgLoading"
        :fetchpriority="imgFetchPriority"
        decoding="async"
      />
      <span v-else :class="textClass">{{ text }}</span>
    </div>
  </div>
</template>

// src/components/atoms/v-avatar.tsx
import type { ReactElement } from 'react';
import type { AvatarSize, VAvatarProps } from '@/types/v-avatar';

interface Props extends VAvatarProps {
  className?: string;
}

const sizeClasses: Record<AvatarSize, string> = {
  xs: 'w-8',
  sm: 'w-12',
  md: 'w-16',
  lg: 'w-24',
  xl: 'w-64',
};

const shortTextClasses: Record<AvatarSize, string> = {
  xs: 'text-xs',
  sm: 'text-base',
  md: 'text-xl',
  lg: 'text-3xl',
  xl: 'text-5xl',
};

const longTextClasses: Record<AvatarSize, string> = {
  xs: 'text-xs',
  sm: 'text-sm',
  md: 'text-base',
  lg: 'text-lg',
  xl: 'text-2xl',
};

export const VAvatar = ({
  src,
  alt = 'avatar',
  size = 'md',
  shape = 'rounded',
  mask = '',
  online = false,
  offline = false,
  placeholder = false,
  text = '',
  ring = false,
  priority = false,
  className,
}: Props): ReactElement => {
  const textClass = text.length > 2 ? longTextClasses[size] : shortTextClasses[size];
  const isPlaceholder = placeholder || !src;
  const avatarClassName = [
    'avatar',
    online && 'avatar-online',
    offline && 'avatar-offline',
    isPlaceholder && 'avatar-placeholder',
    className,
  ]
    .filter(Boolean)
    .join(' ');
  const contentClassName = [
    sizeClasses[size],
    shape,
    mask,
    ring && 'ring-2 ring-primary ring-offset-base-100 ring-offset-2',
    isPlaceholder && 'bg-neutral text-neutral-content',
  ]
    .filter(Boolean)
    .join(' ');

  return (
    <div className={avatarClassName}>
      <div className={contentClassName}>
        {src ? (
          <img
            src={src}
            alt={alt}
            loading={priority ? 'eager' : 'lazy'}
            fetchPriority={priority ? 'high' : 'auto'}
            decoding="async"
          />
        ) : (
          <span className={textClass}>{text}</span>
        )}
      </div>
    </div>
  );
};

export default VAvatar;
