// src/components/atoms/v-button.tsx
import type { ButtonHTMLAttributes, ReactElement, ReactNode } from 'react';
import type { ButtonColor, ButtonSize, ButtonVariant, VButtonProps } from '@/types/v-button';

interface Props extends VButtonProps {
  children?: ReactNode;
  className?: string;
  target?: string;
  rel?: string;
  ariaLabel?: string;
  type?: ButtonHTMLAttributes<HTMLButtonElement>['type'];
}

const colorClasses: Record<ButtonColor, string> = {
  neutral: 'btn-neutral',
  primary: 'btn-primary',
  secondary: 'btn-secondary',
  accent: 'btn-accent',
  info: 'btn-info',
  success: 'btn-success',
  warning: 'btn-warning',
  error: 'btn-error',
};

const variantClasses: Record<ButtonVariant, string> = {
  outline: 'btn-outline',
  dash: 'btn-dash',
  soft: 'btn-soft',
  ghost: 'btn-ghost',
  link: 'btn-link',
};

const sizeClasses: Record<ButtonSize, string> = {
  xs: 'btn-xs',
  sm: 'btn-sm',
  md: '',
  lg: 'btn-lg',
  xl: 'btn-xl',
};

export const VButton = ({
  color,
  variant,
  size = 'md',
  wide = false,
  block = false,
  square = false,
  circle = false,
  active = false,
  disabled = false,
  loading = false,
  tag = 'button',
  href,
  className,
  target,
  rel,
  ariaLabel,
  type = 'button',
  children,
}: Props): ReactElement => {
  const classes = [
    'btn',
    color && colorClasses[color],
    variant && variantClasses[variant],
    sizeClasses[size],
    wide && 'btn-wide',
    block && 'btn-block',
    square && 'btn-square',
    circle && 'btn-circle',
    active && 'btn-active',
    (disabled || loading) && 'btn-disabled cursor-not-allowed',
    className,
  ]
    .filter(Boolean)
    .join(' ');
  const content = loading ? <span className="loading loading-spinner" /> : children;

  if (href || tag === 'a') {
    return (
      <a
        href={href}
        className={classes}
        target={target}
        rel={rel}
        aria-label={ariaLabel}
        aria-disabled={disabled || loading ? 'true' : undefined}
      >
        {content}
      </a>
    );
  }

  return (
    <button type={type} className={classes} aria-label={ariaLabel} disabled={disabled || loading}>
      {content}
    </button>
  );
};

export default VButton;

// src/components/atoms/v-button.vue
<script setup lang="ts">
import { computed } from 'vue';
import type { ButtonColor, ButtonVariant, ButtonSize, VButtonProps } from '@/types/v-button';

const props = withDefaults(defineProps<VButtonProps>(), {
  color: undefined,
  variant: undefined,
  size: 'md',
  wide: false,
  block: false,
  square: false,
  circle: false,
  active: false,
  disabled: false,
  loading: false,
  tag: 'button',
  href: undefined,
  to: undefined,
});

const emit = defineEmits<{
  (e: 'click', event: MouseEvent): void;
}>();

const componentTag = computed(() => {
  if (props.to) {
    return 'router-link';
  }
  if (props.href) {
    return 'a';
  }
  return props.tag;
});

const buttonClasses = computed(() => {
  const colorClasses: Record<ButtonColor, string> = {
    neutral: 'btn-neutral',
    primary: 'btn-primary',
    secondary: 'btn-secondary',
    accent: 'btn-accent',
    info: 'btn-info',
    success: 'btn-success',
    warning: 'btn-warning',
    error: 'btn-error',
  };

  const variantClasses: Record<ButtonVariant, string> = {
    outline: 'btn-outline',
    dash: 'btn-dash',
    soft: 'btn-soft',
    ghost: 'btn-ghost',
    link: 'btn-link',
  };

  const sizeClasses: Record<ButtonSize, string> = {
    xs: 'btn-xs',
    sm: 'btn-sm',
    md: '',
    lg: 'btn-lg',
    xl: 'btn-xl',
  };

  const classes = ['btn'];
  if (props.color) {
    classes.push(colorClasses[props.color]);
  }
  if (props.variant) {
    classes.push(variantClasses[props.variant]);
  }
  if (props.size && props.size !== 'md') {
    classes.push(sizeClasses[props.size]);
  }
  if (props.wide) {
    classes.push('btn-wide');
  }
  if (props.block) {
    classes.push('btn-block');
  }
  if (props.square) {
    classes.push('btn-square');
  }
  if (props.circle) {
    classes.push('btn-circle');
  }
  if (props.active) {
    classes.push('btn-active');
  }
  if (props.disabled || props.loading) {
    classes.push('btn-disabled');
  }
  return classes;
});

const handleClick = (event: MouseEvent) => {
  if (props.disabled || props.loading) {
    event.preventDefault();
    return;
  }
  emit('click', event);
};
</script>

<template>
  <component
    :is="componentTag"
    :class="buttonClasses"
    :href="href"
    :to="to"
    :aria-disabled="disabled || loading"
    @click="handleClick"
  >
    <span v-if="loading" class="loading loading-spinner"></span>
    <slot v-else></slot>
  </component>
</template>

<style>
.btn-disabled {
  cursor: not-allowed;
}
</style>
