// src/components/ui/VButton.vue
<script setup>
import { computed } from 'vue';

const props = defineProps({
  theme: { type: String, default: 'primary' },
  variant: { type: String, default: null }, // ghost, outline, link
  size: { type: String, default: null }, // lg, xs, sm
  wide: { type: Boolean, default: false },
  disabled: { type: Boolean, default: false },
  block: { type: Boolean, default: false },
  loading: { type: Boolean, default: false },
  href: { type: String, default: null },
  to: { type: [String, Object], default: null },
  shape: { type: String, default: null }, // square, circle
});

const buttonElement = computed(() => {
  if (props.href) {
    return 'a';
  } if (props.to) {
    return 'router-link';
  }
  return 'button';
});
const buttonThemes = {
  primary: 'btn-primary',
  secondary: 'btn-secondary',
  accent: 'btn-accent',
  info: 'btn-info',
  success: 'btn-success',
  warning: 'btn-warning',
  error: 'btn-error',
};
const buttonVariants = {
  ghost: 'btn-ghost',
  link: 'btn-link',
  outline: 'btn-outline',
  active: 'btn-active',
};
const buttonSizes = {
  lg: 'btn-lg',
  md: 'btn-md',
  sm: 'btn-sm',
  xs: 'btn-xs',
};
const buttonShapes = {
  circle: 'btn-circle',
  square: 'btn-square',
};
const buttonClass = computed(() => ({
  btn: true,
  [buttonThemes[props.theme]]: true,
  [buttonVariants[props.variant]]: props.variant,
  [buttonSizes[props.size]]: props.size,
  [buttonShapes[props.shape]]: props.shape,
  'btn-wide': props.wide,
  'btn-disabled': props.disabled,
  'btn-block': props.block,
  loading: props.loading,
}));
const buttonAttr = computed(() => ({
  ...(props.to && { to: props.to }),
  ...(props.href && { href: props.href }),
  ...(props.disabled && { disabled: true }),
}));
</script>

<template>
  <component
    :is="buttonElement"
    :class="buttonClass"
    v-bind="buttonAttr"
  >
    <slot />
  </component>
</template>

// src/components/atoms/v-button.tsx
import type { ButtonHTMLAttributes, ReactElement, ReactNode } from 'react';
import type { ButtonColor, ButtonSize, ButtonVariant, VButtonProps } from '@/types/v-button';

interface Props extends VButtonProps {
  children?: ReactNode;
  className?: string;
  target?: string;
  rel?: string;
  ariaLabel?: string;
  type?: ButtonHTMLAttributes<HTMLButtonElement>['type'];
}

const colorClasses: Record<ButtonColor, string> = {
  neutral: 'btn-neutral',
  primary: 'btn-primary',
  secondary: 'btn-secondary',
  accent: 'btn-accent',
  info: 'btn-info',
  success: 'btn-success',
  warning: 'btn-warning',
  error: 'btn-error',
};

const variantClasses: Record<ButtonVariant, string> = {
  outline: 'btn-outline',
  dash: 'btn-dash',
  soft: 'btn-soft',
  ghost: 'btn-ghost',
  link: 'btn-link',
};

const sizeClasses: Record<ButtonSize, string> = {
  xs: 'btn-xs',
  sm: 'btn-sm',
  md: '',
  lg: 'btn-lg',
  xl: 'btn-xl',
};

export const VButton = ({
  color,
  variant,
  size = 'md',
  wide = false,
  block = false,
  square = false,
  circle = false,
  active = false,
  disabled = false,
  loading = false,
  tag = 'button',
  href,
  className,
  target,
  rel,
  ariaLabel,
  type = 'button',
  children,
}: Props): ReactElement => {
  const classes = [
    'btn',
    color && colorClasses[color],
    variant && variantClasses[variant],
    sizeClasses[size],
    wide && 'btn-wide',
    block && 'btn-block',
    square && 'btn-square',
    circle && 'btn-circle',
    active && 'btn-active',
    (disabled || loading) && 'btn-disabled cursor-not-allowed',
    className,
  ]
    .filter(Boolean)
    .join(' ');
  const content = loading ? <span className="loading loading-spinner" /> : children;

  if (href || tag === 'a') {
    return (
      <a
        href={href}
        className={classes}
        target={target}
        rel={rel}
        aria-label={ariaLabel}
        aria-disabled={disabled || loading ? 'true' : undefined}
      >
        {content}
      </a>
    );
  }

  return (
    <button type={type} className={classes} aria-label={ariaLabel} disabled={disabled || loading}>
      {content}
    </button>
  );
};

export default VButton;
