// src/components/atoms/v-card.vue
<script setup lang="ts">
import { computed } from 'vue';
import type { CardSize, ResponsiveSize, VCardProps } from '@/types/v-card';

const props = withDefaults(defineProps<VCardProps>(), {
  title: '',
  bordered: false,
  dashed: false,
  side: false,
  imageFull: false,
  size: 'md',
  imageSrc: '',
  imageAlt: 'card image',
  imageBottom: false,
  centered: false,
  color: '',
  responsive: false,
  figurePadding: false,
  figureRounded: false,
});

const cardClasses = computed(() => {
  const classes: (string | Record<string, boolean>)[] = ['card'];

  const sizeClassMap: Record<CardSize, string> = {
    xs: 'card-xs',
    sm: 'card-sm',
    md: 'card-md',
    lg: 'card-lg',
    xl: 'card-xl',
  };

  if (typeof props.size === 'string') {
    const sizeClass = sizeClassMap[props.size];
    if (sizeClass && props.size !== 'md') {
      classes.push(sizeClass);
    }
  } else if (typeof props.size === 'object') {
    for (const screen in props.size) {
      const size = props.size[screen as keyof ResponsiveSize];
      if (size) {
        const sizeClass = sizeClassMap[size];
        if (screen === 'default') {
          if (size !== 'md') {
            classes.push(sizeClass);
          }
        } else {
          classes.push(`${screen}:${sizeClass}`);
        }
      }
    }
  }

  classes.push({
    'card-border': props.bordered,
    'card-dash': props.dashed,
    'card-side': props.side,
    'lg:card-side': props.responsive,
    'image-full': props.imageFull,
  });

  if (props.color) {
    classes.push(props.color);
  }

  return classes;
});

const figureClasses = computed(() => ({
  'px-10 pt-10': props.figurePadding,
}));

const bodyClasses = computed(() => ({
  'card-body': true,
  'items-center text-center': props.centered,
}));
</script>

<template>
  <div :class="cardClasses">
    <figure v-if="imageSrc && !imageBottom" :class="figureClasses">
      <img :src="imageSrc" :alt="imageAlt" :class="{ 'rounded-box': figureRounded }" />
    </figure>
    <slot name="figure"></slot>

    <div :class="bodyClasses">
      <h2 v-if="title" class="card-title">
        {{ title }}
        <slot name="badge"></slot>
      </h2>
      <slot name="title"></slot>
      <slot></slot>
      <div v-if="$slots.actions" class="card-actions">
        <slot name="actions"></slot>
      </div>
    </div>

    <figure v-if="imageSrc && imageBottom" :class="figureClasses">
      <img :src="imageSrc" :alt="imageAlt" :class="{ 'rounded-box': figureRounded }" />
    </figure>
  </div>
</template>

// src/components/atoms/v-card.tsx
import type { ReactElement, ReactNode } from 'react';
import type { CardSize, ResponsiveSize, VCardProps } from '@/types/v-card';

interface Props extends VCardProps {
  children?: ReactNode;
  className?: string;
  figure?: ReactNode;
  badge?: ReactNode;
  titleContent?: ReactNode;
  actions?: ReactNode;
}

const sizeClasses: Record<CardSize, string> = {
  xs: 'card-xs',
  sm: 'card-sm',
  md: '',
  lg: 'card-lg',
  xl: 'card-xl',
};

const responsiveSizeClasses: Record<keyof ResponsiveSize, Record<CardSize, string>> = {
  default: sizeClasses,
  sm: {
    xs: 'sm:card-xs',
    sm: 'sm:card-sm',
    md: '',
    lg: 'sm:card-lg',
    xl: 'sm:card-xl',
  },
  md: {
    xs: 'md:card-xs',
    sm: 'md:card-sm',
    md: '',
    lg: 'md:card-lg',
    xl: 'md:card-xl',
  },
  lg: {
    xs: 'lg:card-xs',
    sm: 'lg:card-sm',
    md: '',
    lg: 'lg:card-lg',
    xl: 'lg:card-xl',
  },
  xl: {
    xs: 'xl:card-xs',
    sm: 'xl:card-sm',
    md: '',
    lg: 'xl:card-lg',
    xl: 'xl:card-xl',
  },
};

export const VCard = ({
  title = '',
  bordered = false,
  dashed = false,
  side = false,
  imageFull = false,
  size = 'md',
  imageSrc = '',
  imageAlt = 'card image',
  imageBottom = false,
  centered = false,
  color = '',
  responsive = false,
  figurePadding = false,
  figureRounded = false,
  className,
  figure,
  badge,
  titleContent,
  actions,
  children,
}: Props): ReactElement => {
  const responsiveClasses =
    typeof size === 'object'
      ? Object.entries(size).map(([screen, cardSize]) =>
          cardSize ? responsiveSizeClasses[screen as keyof ResponsiveSize][cardSize] : '',
        )
      : [];
  const cardSizeClass = typeof size === 'string' ? sizeClasses[size] : responsiveClasses.join(' ');
  const classes = [
    'card',
    cardSizeClass,
    bordered && 'card-border',
    dashed && 'card-dash',
    side && 'card-side',
    responsive && 'lg:card-side',
    imageFull && 'image-full',
    color,
    className,
  ]
    .filter(Boolean)
    .join(' ');
  const figureClassName = figurePadding ? 'px-10 pt-10' : undefined;
  const imageClassName = figureRounded ? 'rounded-box' : undefined;
  const image = imageSrc ? (
    <figure className={figureClassName}>
      <img src={imageSrc} alt={imageAlt} className={imageClassName} />
    </figure>
  ) : null;

  return (
    <div className={classes}>
      {!imageBottom && image}
      {figure}
      <div
        className={['card-body', centered && 'items-center text-center'].filter(Boolean).join(' ')}
      >
        {title && (
          <h2 className="card-title">
            {title}
            {badge}
          </h2>
        )}
        {titleContent}
        {children}
        {actions && <div className="card-actions">{actions}</div>}
      </div>
      {imageBottom && image}
    </div>
  );
};

export default VCard;
