// src/components/atoms/v-navbar.tsx
import type { ReactElement, ReactNode } from 'react';

interface Props {
  className?: string;
  start?: ReactNode;
  center?: ReactNode;
  end?: ReactNode;
}

export const VNavbar = ({ className, start, center, end }: Props): ReactElement => (
  <div className={['navbar', className].filter(Boolean).join(' ')}>
    <div className="navbar-start">{start}</div>
    <div className="navbar-center">{center}</div>
    <div className="navbar-end">{end}</div>
  </div>
);

export default VNavbar;

// src/components/atoms/v-navbar.vue
<script setup lang="ts">
defineSlots<{
  start: () => any;
  center: () => any;
  end: () => any;
}>();
</script>

<template>
  <div class="navbar">
    <div class="navbar-start">
      <slot name="start"></slot>
    </div>
    <div class="navbar-center">
      <slot name="center"></slot>
    </div>
    <div class="navbar-end">
      <slot name="end"></slot>
    </div>
  </div>
</template>
