// src/components/molecules/social-links.tsx
import type { ReactElement } from 'react';
import VIcon from '@/components/atoms/v-icon';
import { profile } from '@/data/content';

interface Props {
  className?: string;
}

const userInfo = profile;
const socialLinks = [
  { name: 'github', label: 'GitHub profile', url: userInfo.github, icon: 'fa-github' },
  { name: 'linkedin', label: 'LinkedIn profile', url: userInfo.linkedin, icon: 'fa-linkedin' },
  { name: 'devto', label: 'Dev.to profile', url: userInfo.devto, icon: 'fa-dev' },
  { name: 'twitter', label: 'X (Twitter) profile', url: userInfo.twitter, icon: 'fa-twitter' },
];

export const SocialLinks = ({ className }: Props): ReactElement => (
  <div className={['flex items-center gap-2', className].filter(Boolean).join(' ')}>
    {socialLinks.map((link) => (
      <a
        key={link.name}
        href={link.url}
        target="_blank"
        rel="noopener noreferrer"
        aria-label={link.label}
        className="btn btn-circle btn-ghost"
      >
        <VIcon name={link.icon} className="h-5 w-5" />
      </a>
    ))}
  </div>
);

export default SocialLinks;

// src/components/molecules/social-links.vue
<script setup lang="ts">
import { computed } from 'vue';
import { useUserStore } from '@/stores/user.store';
import VButton from '@/components/atoms/v-button.vue';
import VIcon from '@/components/atoms/v-icon.vue';

const userStore = useUserStore();
const socialLinks = computed(() => [
  {
    name: 'github',
    label: 'GitHub profile',
    url: userStore.userInfo.github,
    icon: 'fa-github',
  },
  {
    name: 'linkedin',
    label: 'LinkedIn profile',
    url: userStore.userInfo.linkedin,
    icon: 'fa-linkedin',
  },
  {
    name: 'devto',
    label: 'Dev.to profile',
    url: userStore.userInfo.devto,
    icon: 'fa-dev',
  },
  {
    name: 'twitter',
    label: 'X (Twitter) profile',
    url: userStore.userInfo.twitter,
    icon: 'fa-twitter',
  },
]);
</script>

<template>
  <div class="flex items-center gap-2">
    <v-button
      v-for="link in socialLinks"
      :key="link.name"
      tag="a"
      :href="link.url"
      target="_blank"
      rel="noopener noreferrer"
      :aria-label="link.label"
      variant="ghost"
      circle
    >
      <v-icon :name="link.icon" class="h-5 w-5" />
    </v-button>
  </div>
</template>
