// src/components/molecules/v-tech-badge.vue
<script setup lang="ts">
import type { VTechBadgeProps } from '@/types/v-tech-badge';
import VBadge from '@/components/atoms/v-badge.vue';
import VIcon from '@/components/atoms/v-icon.vue';

defineProps<VTechBadgeProps>();
</script>

<template>
  <v-badge variant="dash" color="secondary">
    <v-icon :name="technology.icon" />
    <span>{{ technology.name }}</span>
  </v-badge>
</template>

// src/components/molecules/v-tech-badge.tsx
import type { ReactElement } from 'react';
import VBadge from '@/components/atoms/v-badge';
import VIcon from '@/components/atoms/v-icon';
import type { VTechBadgeProps } from '@/types/v-tech-badge';

export const VTechBadge = ({ technology }: VTechBadgeProps): ReactElement => (
  <VBadge variant="dash" color="secondary">
    <VIcon name={technology.icon} />
    <span>{technology.name}</span>
  </VBadge>
);

export default VTechBadge;
