// src/components/organisms/footer-section.vue
<script setup lang="ts">
import { computed } from 'vue';
import SocialLinks from '@/components/molecules/social-links.vue';

const currentYear = computed(() => new Date().getFullYear());
</script>

<template>
  <footer class="bg-base-200" aria-label="Site footer">
    <div class="container py-12">
      <div class="flex flex-col sm:flex-row justify-between items-center gap-4">
        <div class="flex items-center space-x-4">
          <p class="text-base-content-muted text-sm">
            &copy; {{ currentYear }} Ibrahim Turan. All rights reserved.
          </p>
        </div>
        <social-links />
      </div>
    </div>
  </footer>
</template>

// src/components/organisms/footer-section.tsx
import type { ReactElement } from 'react';
import SocialLinks from '@/components/molecules/social-links';

export const FooterSection = (): ReactElement => (
  <footer className="bg-base-200" aria-label="Site footer">
    <div className="container py-12">
      <div className="flex flex-col items-center justify-between gap-4 sm:flex-row">
        <div className="flex items-center space-x-4">
          <p className="text-sm text-base-content-muted">
            &copy; {new Date().getFullYear()} Ibrahim Turan. All rights reserved.
          </p>
        </div>
        <SocialLinks />
      </div>
    </div>
  </footer>
);

export default FooterSection;
